const {DataTypes}=require("sequelize")
const {sequelize}=require("../database/database")

const Reserva=sequelize.define("Reserva",{
    idReserva:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        autoIncrement:true
    },
    nombreUsuario:{
        type:DataTypes.STRING,
        allowNull:true
    },
    idPropietario:{
        type:DataTypes.STRING,
        allowNull:true
    },
    estado:{
        type:DataTypes.STRING
    },
    numeroConfirmacion:{
        type:DataTypes.STRING,
    },
    fechaInicio:{
        type:DataTypes.DATE,
    },
    fechaFin:{
        type:DataTypes.DATE,
    },
    horaCheckIn:{
        type:DataTypes.TIME(7),
    },
    horaCheckOut:{
        type:DataTypes.TIME(7),
    },
    numeroAcompañantes:{
        type:DataTypes.INTEGER,
    },
    servicioDesayuno:{
        type:DataTypes.STRING(2),
    },
    servicioAlmuerzo:{
        type:DataTypes.STRING(2),
    },
    servicioCena:{
        type:DataTypes.STRING(2),
    },
    servicioParqueadero:{
        type:DataTypes.STRING(2),
    },
    idHabitacionReservada:{
        type:DataTypes.INTEGER,
    },
    servicioTransporte:{
        type:DataTypes.STRING(2),
    },
    total:{
        type:DataTypes.FLOAT,
    }
},{timestamps:false})

module.exports={Reserva}